### ISSUE TITLE
Faile assign basic materials at blender 3.6

### ISSUE THREAD

**Issue by NaughtDZ** [hs2blenderimport/hs2-blender-importer#2]
Traceback (most recent call last):
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hs2-blender-importer-main\__init__.py", line 773, in execute
    BodyMaterialBuilder(context, material).CreateMaterial()
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hs2-blender-importer-main\__init__.py", line 842, in CreateMaterial
    self.MainTexture()
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hs2-blender-importer-main\__init__.py", line 920, in MainTexture
    self.material.node_tree.links.new(mix_nip_with_main.outputs[0], self.shader.inputs[0])
AttributeError: 'NoneType' object has no attribute 'inputs'
閿欒: Python: Traceback (most recent call last):
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hs2-blender-importer-main\__init__.py", line 773, in execute
    BodyMaterialBuilder(context, material).CreateMaterial()
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hs2-blender-importer-main\__init__.py", line 842, in CreateMaterial
    self.MainTexture()
  File "C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hs2-blender-importer-main\__init__.py", line 920, in MainTexture
    self.material.node_tree.links.new(mix_nip_with_main.outputs[0], self.shader.inputs[0])
AttributeError: 'NoneType' object has no attribute 'inputs'

**Comment by CBlues** [comment]
Same, that happens in the newer versions of blender, you need to try it in blender 3.2 and it should work just fine
